"use client";

import Image from "next/image";
import { AnimateIn } from "@/components/animate-in";
import { SiteFooter, SiteHeader, type Locale } from "@/components/site-shell";
import { Button, Container, Label } from "@/components/ui";
import { usePersistentLocale } from "@/components/use-persistent-locale";
import backgroundPattern from "@/assets/prdi/background-pattern.png";

const principles = [
  ["01", "Consortium-led", "Local, international and diaspora entrepreneurs govern it together, so the pipeline reaches beyond Palestine from day one."],
  ["02", "University-hosted", "Labs sit inside the universities that already own them, which keeps capital cost close to zero."],
  ["03", "Industry-funded", "Manufacturers pay for defined R&D deliverables — not for research in general."]
];

const structure = [
  ["Ramallah headquarters", "Governance, contracting, IP, quality, and the commercial pipeline including international partners."],
  ["University branches", "Labs, faculty expertise and graduate researchers, assembled per project inside major Palestinian universities."],
  ["Industrial clients", "Manufacturers and SMEs buying defined R&D deliverables, in Palestine and across the region."]
];

const sectors = [["Agriculture", "Yield, irrigation, post-harvest"], ["Energy", "Solar, storage, efficiency"], ["Pharmaceuticals", "Formulation, GMP, export"], ["Food processing", "Shelf life, new lines, HACCP"], ["ICT", "AI systems, data products"]];

const services = [
  ["Product development", "Turning lab formulations or functional prototypes into market-grade products tailored for mass production."],
  ["Process innovation", "Redesigning production lines for efficiency, yield optimization, automated visual testing, and regional scale."],
  ["Research capacity on demand", "Providing enterprises with top-tier scientific engineering, MLOps, and physical lab access per project."],
  ["IP & commercialization", "Defensively packaging research results, patent filing support, spin-off strategy, and regional IP transfer."],
  ["Technology & know-how transfer", "Adapting international research standards, certifications, and technical know-how into Palestinian manufacturers."]
];

const partners = [["CETIC", "Applied ICT research centre", "Belgium", "Research"], ["NIZO", "Food and health research", "Netherlands", "Research"], ["Agritech", "National research centre", "Italy", "Research"], ["QRDI Council", "Qatar R&D & Innovation", "Qatar", "Public R&D"], ["CHU Santo António", "University hospital centre", "Porto", "Clinical"]];

const ecosystem = [
  { title: "STARTUPS & VCS", input: "Ventures and capital", output: "Spin-outs and IP", tint: "border-[#ef4444] bg-[#fee2e2] text-[#ef4444]", pos: "left-[12%] top-[12%]" },
  { title: "UNIVERSITIES", input: "Labs and researchers", output: "Funded projects", tint: "border-[#10b981] bg-[#ecfdf5] text-[#10b981]", pos: "left-1/2 top-[3%] -translate-x-1/2" },
  { title: "INDUSTRY & SMES", input: "Real problems", output: "Better products", tint: "border-[#3b82f6] bg-[#eff6ff] text-[#3b82f6]", pos: "right-[9%] top-[14%]" },
  { title: "DIASPORA NETWORK", input: "Markets and know-how", output: "Delivery arm", tint: "border-[#ea8a00] bg-[#ffedd5] text-[#ea8a00]", pos: "bottom-[12%] left-[12%]" },
  { title: "DONORS & DFIS", input: "Phase 1 capital", output: "A self-funding centre", tint: "border-[#9333ea] bg-[#f3e8ff] text-[#9333ea]", pos: "bottom-[1%] left-1/2 -translate-x-1/2" },
  { title: "GOVERNMENT", input: "Policy and standards", output: "High-value jobs", tint: "border-[#d9aa00] bg-[#fef3c7] text-[#d9aa00]", pos: "bottom-[12%] right-[9%]" }
];

function Dashboard() {
  return <div className="w-full max-w-[480px] overflow-hidden rounded-[24px] border border-[#21463e] bg-[#071f1b] shadow-[0_32px_80px_rgba(0,0,0,0.25)]"><div className="flex items-center justify-between border-b border-[#163a33] bg-white/[0.03] px-4 py-[14px]"><div className="flex gap-[7px]"><i className="h-2.5 w-2.5 rounded-full bg-[#21463e]" /><i className="h-2.5 w-2.5 rounded-full bg-[#1e6d69]" /><i className="h-2.5 w-2.5 rounded-full bg-brand-mint" /></div><span className="font-poppins text-[11px] font-extrabold tracking-[0.14em] text-[#6e867e]">PRDI DASHBOARD</span></div><div className="grid min-h-[403px] grid-cols-2 gap-[18px] p-[18px]"><div className="rounded-[14px] border border-[#163a33] bg-white/[0.04] p-4"><p className="text-[13px] font-bold text-brand-mint">Sectors Served</p><strong className="mt-2 block text-[28px]">5</strong><p className="mt-3 text-[10px] leading-4 text-muted-dark">Agriculture · Energy · Pharma · Food · ICT</p></div><div className="rounded-[14px] border border-[#163a33] bg-white/[0.04] p-4"><p className="text-[13px] font-bold text-brand-mint">Partner Talks</p><strong className="mt-2 block text-[28px]">7</strong><p className="mt-3 text-[10px] leading-4 text-muted-dark">International research partners</p></div><div className="col-span-2 rounded-[14px] border border-[#163a33] bg-white/[0.04] p-4"><div className="flex items-center justify-between text-[13px]"><span className="font-semibold text-muted-dark">R&D Service Model</span><span className="text-[11px] font-bold text-brand-mint">LIVE</span></div><div className="mt-3 h-1 rounded-full bg-[#163a33]"><div className="h-full w-[30%] rounded-full bg-brand-mint" /></div><div className="mt-2 h-[92px] border-b-4 border-brand-mint/30" /><p className="mt-2 text-[10px] text-[#6e867e]">Contract R&D across university-hosted labs in Palestine</p></div></div></div>;
}

function SectionIntro({ label, title, body, dark = false }: { label: string; title: string; body?: string; dark?: boolean }) {
  return <div className={`grid gap-7 ${body ? "lg:grid-cols-[1fr_0.9fr] lg:gap-14" : ""} ${dark ? "text-white" : "text-[#031915]"}`}><div><Label dark={dark}>{label}</Label><h2 className={`mt-5 ${body ? "max-w-[700px]" : "max-w-[900px]"} text-[34px] font-black leading-[1.08] tracking-[-0.04em] sm:text-[45px] md:text-[52px]`}>{title}</h2></div>{body ? <p className={`max-w-[580px] text-[18px] leading-8 lg:pt-9 ${dark ? "text-muted-dark" : "text-muted-light"}`}>{body}</p> : null}</div>;
}

function EcosystemCard({ item }: { item: (typeof ecosystem)[number] }) {
  return <article className={`w-full max-w-[220px] rounded-[10px] border-l-[3px] p-[13px] text-[#111827] shadow-sm ${item.tint}`}><h3 className="text-[11px] font-bold tracking-[0.1em]">{item.title}</h3><span className="mt-2 block text-[9px] font-semibold tracking-[0.08em] text-[#4b5563]">IN</span><p className="text-[13px] font-medium">{item.input}</p><span className="mt-2 block text-[9px] font-semibold tracking-[0.08em] text-[#4b5563]">OUT</span><p className="text-[13px] font-medium">{item.output}</p></article>;
}

function PrdiPageContent({ locale, setLocale }: { locale: Locale; setLocale: (locale: Locale) => void }) {
  return <div lang="en"><SiteHeader active="PRDI" allowArabic={false} locale={locale} setLocale={setLocale} /><main>
    <section className="relative overflow-hidden bg-brand-dark py-20 md:py-[92px]"><div className="absolute right-[-110px] top-[-72px] h-[450px] w-[637px] opacity-10"><Image alt="" className="h-full w-full object-cover" fill sizes="637px" src={backgroundPattern} /></div><div className="absolute right-[15%] top-[-190px] h-[450px] w-[450px] rounded-full bg-brand-mint/[0.13] blur-3xl" /><Container className="relative grid items-center gap-12 lg:grid-cols-[1.38fr_1fr] lg:gap-[96px]"><AnimateIn variant="left"><div><div className="inline-flex items-center gap-2.5 rounded-full border border-[#21463e] px-[14px] py-2 text-[11px] font-semibold tracking-[0.05em] text-muted-dark"><i className="h-[7px] w-[7px] rounded-full bg-brand-green shadow-[0_0_14px_#5be45e]" />PRDI · RAMALLAH — PALESTINE</div><h1 className="mt-5 max-w-[720px] font-poppins text-[39px] font-extrabold leading-[1.13] tracking-[-0.04em] sm:text-[50px] md:text-[56px]"><span className="text-gradient-green">Palestine Research, Development &amp; Innovation Center</span> (PRDI)</h1><p className="mt-5 max-w-[690px] text-[18px] leading-[1.7] text-muted-dark md:text-[20px]">Applied-research center turning Palestinian research into market-ready products and high-value jobs. Established and operated under <b className="text-white">Adopters AI</b>.</p><div className="mt-8 flex flex-wrap gap-4"><Button href="#what-it-is">Learn more →</Button><Button href="/contact" variant="outline">Book a call</Button></div></div></AnimateIn><AnimateIn variant="right"><Dashboard /></AnimateIn></Container></section>
    <section className="bg-white py-24 md:py-[118px]" id="what-it-is"><Container><SectionIntro label="01 · What it is" title="Research that reaches the market" body="PRDI is an applied-research center headquartered in Ramallah, designed to bridge the gap between academic innovation and market viability. We mobilize global and diaspora resources to fuel sustainable high-value job creation locally." /><div className="mt-14 grid gap-5 md:grid-cols-3">{principles.map(([number, title, body], index) => <AnimateIn delay={index * 90} key={number} variant="up"><article className="h-full min-h-[258px] rounded-[16px] border border-border-light bg-white p-8 sm:p-[39px]"><span className="inline-flex h-[42px] w-[42px] items-center justify-center rounded-[14px] bg-[#031915] text-sm font-bold text-[#f4f6f5]">{number}</span><h3 className="mt-5 text-[21px] font-extrabold" style={{ color: "#031915" }}>{title}</h3><p className="mt-3 text-[15px] leading-6 text-muted-light">{body}</p></article></AnimateIn>)}</div></Container></section>
    <section className="bg-brand-dark py-24 text-white md:py-[160px]"><Container><SectionIntro dark label="02 · Structure" title="One headquarters, many campuses" /><div className="mt-16 grid gap-6 md:grid-cols-3">{structure.map(([title, body], index) => <AnimateIn delay={index * 90} key={title} variant="up"><article className="h-full rounded-[16px] border border-[#21463e] bg-[#071f1b] p-8 sm:p-[33px]"><h3 className="text-[22px] font-extrabold text-brand-mint">{title}</h3><p className="mt-4 text-[15px] leading-6 text-muted-dark">{body}</p></article></AnimateIn>)}</div><div className="mt-14 border-t border-[#21463e] pt-7"><p className="text-[12px] font-bold tracking-[0.08em] text-muted-dark">SECTORS SERVED — AND WHAT THEY BUY</p><div className="mt-6 flex flex-wrap justify-center gap-3">{sectors.map(([name, detail]) => <span className="flex w-full items-center rounded-full border border-[#21463e] bg-[#0a2e27] px-5 py-3 text-sm text-white sm:inline-flex sm:w-auto" key={name}><b className="shrink-0" style={{ color: "#5be45e" }}>{name}</b><i className="mx-3 h-4 shrink-0 border-l border-[#21463e]" /><span className="min-w-0" style={{ color: "#a7bdb6" }}>{detail}</span></span>)}</div></div></Container></section>
    <section className="bg-white py-24 md:py-[118px]"><Container><SectionIntro label="03 · Ecosystem" title="At the center of the ecosystem" /><AnimateIn className="mt-12" variant="up"><div className="relative hidden h-[750px] overflow-hidden rounded-[28px] bg-white lg:block"><div className="absolute left-1/2 top-1/2 h-[2px] w-[65%] -translate-x-1/2 -translate-y-1/2 rotate-[28deg] border-t border-dashed border-[#79b8ab]" /><div className="absolute left-1/2 top-1/2 h-[2px] w-[65%] -translate-x-1/2 -translate-y-1/2 -rotate-[28deg] border-t border-dashed border-[#79b8ab]" /><div className="absolute left-1/2 top-[20%] h-[60%] border-l border-dashed border-[#79b8ab]" />{ecosystem.map((item) => <div className={`absolute ${item.pos}`} key={item.title}><EcosystemCard item={item} /></div>)}<span className="absolute left-1/2 top-[38%] h-3 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white bg-brand-mint" /><span className="absolute left-[40%] top-[44%] h-3 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white bg-brand-mint" /><span className="absolute left-[60%] top-[44%] h-3 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white bg-brand-mint" /><span className="absolute left-[40%] top-[56%] h-3 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white bg-brand-mint" /><span className="absolute left-[60%] top-[56%] h-3 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white bg-brand-mint" /><span className="absolute bottom-[38%] left-1/2 h-3 w-3 -translate-x-1/2 translate-y-1/2 rounded-full border-2 border-white bg-brand-mint" /><div className="absolute left-1/2 top-1/2 flex h-[170px] w-[170px] -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border-2 border-brand-mint bg-[#f2fffa]"><div className="flex h-[130px] w-[130px] flex-col items-center justify-center rounded-full bg-[#101827] text-center"><strong className="text-2xl text-brand-mint">PRDI</strong><span className="mt-1 text-[9px] text-white">Ramallah HQ</span></div></div></div><div className="grid justify-items-center gap-4 lg:hidden"><div className="flex h-32 w-32 flex-col items-center justify-center rounded-full border-2 border-brand-mint bg-[#f2fffa]"><div className="flex h-24 w-24 flex-col items-center justify-center rounded-full bg-[#101827] text-center"><strong className="text-xl text-brand-mint">PRDI</strong><span className="mt-1 text-[9px] text-white">Ramallah HQ</span></div></div>{ecosystem.map((item) => <EcosystemCard item={item} key={item.title} />)}</div></AnimateIn></Container></section>
    <section className="bg-brand-dark py-24 text-white md:py-[118px]"><Container><AnimateIn variant="up"><div className="grid gap-8 lg:grid-cols-[0.95fr_1fr] lg:items-start"><div><Label dark>04 &middot; Services</Label><h2 className="mt-5 max-w-[700px] text-[36px] font-black leading-[1.08] tracking-[-0.04em] sm:text-[46px] md:text-[54px]">Applied R&D as a service</h2><p className="mt-5 max-w-[680px] text-[17px] leading-8 text-muted-dark">PRDI does one thing and does it deeply: contract research and development for industry.</p></div><div className="self-start lg:pt-0"><div className="flex min-h-[64px] items-center justify-center rounded-[14px] border border-[#21463e] bg-[#0b2c26] px-5 text-center text-[16px] text-brand-mint sm:text-[18px]">Agriculture &middot; Energy &middot; Pharmaceuticals &middot; Food processing &middot; ICT</div></div></div></AnimateIn><div className="mt-16 grid gap-5 sm:grid-cols-2 lg:grid-cols-5">{services.map(([title, body], index) => <AnimateIn delay={index * 70} key={title} variant="up"><article className="h-full min-h-[275px] rounded-[14px] border border-[#21463e] bg-white/[0.035] p-7"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#164c3e] text-sm font-bold text-brand-mint">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-5 text-[16px] font-extrabold leading-[22px]">{title}</h3><p className="mt-4 text-[13px] leading-[21px] text-muted-dark">{body}</p></article></AnimateIn>)}</div></Container></section>    <section className="bg-white py-24 md:py-[118px]"><Container><SectionIntro label="05 · Partners" title="Conversations already under way" body="Seven organisations · all at exploratory stage" /><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{partners.map(([name, description, country, type], index) => <AnimateIn delay={index * 80} key={name} variant="up"><article className="flex h-full min-h-[217px] flex-col rounded-[14px] border border-border-light bg-[#fcfdfc] p-7"><div className="flex h-12 w-20 items-center justify-center rounded-md bg-[#e6f0ed] text-xs font-black tracking-wide text-[#1d695e]">{name.slice(0, 4)}</div><h3 className="mt-4 text-[19px] font-extrabold text-[#031915]">{name}</h3><p className="mt-1 text-sm text-muted-light">{description}</p><p className="mt-auto pt-5 text-xs text-[#6c7d77]">{country}<span className="mx-2 text-[#c7d1cd]">|</span>{type}</p></article></AnimateIn>)}</div></Container></section>
    <section className="bg-brand-dark py-20 md:py-[118px]"><Container><div className="relative overflow-hidden rounded-[24px] bg-[linear-gradient(110deg,#78e85c_0%,#5cdf80_55%,#69dfb2_100%)] px-7 py-12 text-[#031915] shadow-[0_24px_60px_rgba(3,25,21,0.18)] sm:px-12 lg:flex lg:items-center lg:justify-between lg:px-14"><div className="absolute -right-16 -top-24 h-[340px] w-[340px] rounded-full border-[32px] border-[#0c4e3e]/15" /><div className="relative max-w-[700px]"><h2 className="text-[34px] font-black leading-[1.1] md:text-[48px]">Ready to partner with PRDI?</h2><p className="mt-4 text-[17px] leading-7 text-[#11372d]">Let&apos;s discuss how we can support your industrial challenges, explore joint IP ventures, or scale national R&D infrastructure.</p></div><div className="relative mt-8 grid gap-3 sm:grid-cols-2 lg:mt-0 lg:w-[342px] lg:grid-cols-1"><Button href="/assessment" variant="dark" className="w-full">Take assessment →</Button><Button href="/contact" variant="light" className="w-full">Book a call</Button></div></div></Container></section>
  </main><SiteFooter allowArabic={false} locale={locale} /></div>;
}

export function PrdiPage() {
  const [locale, setLocale] = usePersistentLocale();
  return <PrdiPageContent locale={locale} setLocale={setLocale} />;
}
